<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedStripData.proto

namespace GPBMetadata;

class LedStripData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
í
LedStripData.proto"€
LedStripData
boardNumber (
stripNumber (
startLedNumber (
endLedNumber (
Colour (2.RgbData"3
RgbData
red (
green (
blue ("
Respond
code (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

