<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedStripData.proto

namespace GPBMetadata;

class LedStripData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
∂
LedStripData.proto"Ñ
LedStripData_t
boardNumber (
stripNumber (
startLedNumber (
endLedNumber (
Colour (2
.RgbData_t"5
	RgbData_t
red (
green (
blue ("
	Respond_t
code ("
Item_t
type ("ã

Resistor_t

partNumber (
package (

resistance (
	tolerance (
power (

maxVoltage (
amount ("ê
Capacitor_t

partNumber (
package (
capacitance (
	tolerance (
nullPlug (

maxVoltage (
amount ("Ö
BJT_t

partNumber (
package (
	structure (

vColEmiMax (
	colCurMax (
power (
amount (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

