<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedStripData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>BJT_t</code>
 */
class BJT_t extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 partNumber = 1;</code>
     */
    protected $partNumber = 0;
    /**
     * Generated from protobuf field <code>uint32 package = 2;</code>
     */
    protected $package = 0;
    /**
     * Generated from protobuf field <code>uint32 structure = 3;</code>
     */
    protected $structure = 0;
    /**
     * Generated from protobuf field <code>uint32 vColEmiMax = 4;</code>
     */
    protected $vColEmiMax = 0;
    /**
     * Generated from protobuf field <code>uint32 colCurMax = 5;</code>
     */
    protected $colCurMax = 0;
    /**
     * Generated from protobuf field <code>uint32 power = 6;</code>
     */
    protected $power = 0;
    /**
     * Generated from protobuf field <code>uint32 amount = 7;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $partNumber
     *     @type int $package
     *     @type int $structure
     *     @type int $vColEmiMax
     *     @type int $colCurMax
     *     @type int $power
     *     @type int $amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LedStripData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 partNumber = 1;</code>
     * @return int
     */
    public function getPartNumber()
    {
        return $this->partNumber;
    }

    /**
     * Generated from protobuf field <code>uint32 partNumber = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPartNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->partNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 package = 2;</code>
     * @return int
     */
    public function getPackage()
    {
        return $this->package;
    }

    /**
     * Generated from protobuf field <code>uint32 package = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkUint32($var);
        $this->package = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 structure = 3;</code>
     * @return int
     */
    public function getStructure()
    {
        return $this->structure;
    }

    /**
     * Generated from protobuf field <code>uint32 structure = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStructure($var)
    {
        GPBUtil::checkUint32($var);
        $this->structure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 vColEmiMax = 4;</code>
     * @return int
     */
    public function getVColEmiMax()
    {
        return $this->vColEmiMax;
    }

    /**
     * Generated from protobuf field <code>uint32 vColEmiMax = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setVColEmiMax($var)
    {
        GPBUtil::checkUint32($var);
        $this->vColEmiMax = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 colCurMax = 5;</code>
     * @return int
     */
    public function getColCurMax()
    {
        return $this->colCurMax;
    }

    /**
     * Generated from protobuf field <code>uint32 colCurMax = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setColCurMax($var)
    {
        GPBUtil::checkUint32($var);
        $this->colCurMax = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 power = 6;</code>
     * @return int
     */
    public function getPower()
    {
        return $this->power;
    }

    /**
     * Generated from protobuf field <code>uint32 power = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPower($var)
    {
        GPBUtil::checkUint32($var);
        $this->power = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 amount = 7;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>uint32 amount = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->amount = $var;

        return $this;
    }

}

