<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedStripData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Capacitor_t</code>
 */
class Capacitor_t extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 partNumber = 1;</code>
     */
    protected $partNumber = 0;
    /**
     * Generated from protobuf field <code>uint32 package = 2;</code>
     */
    protected $package = 0;
    /**
     * Generated from protobuf field <code>uint32 capacitance = 3;</code>
     */
    protected $capacitance = 0;
    /**
     * Generated from protobuf field <code>uint32 tolerance = 4;</code>
     */
    protected $tolerance = 0;
    /**
     * Generated from protobuf field <code>uint32 nullPlug = 5;</code>
     */
    protected $nullPlug = 0;
    /**
     * Generated from protobuf field <code>uint32 maxVoltage = 6;</code>
     */
    protected $maxVoltage = 0;
    /**
     * Generated from protobuf field <code>uint32 amount = 7;</code>
     */
    protected $amount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $partNumber
     *     @type int $package
     *     @type int $capacitance
     *     @type int $tolerance
     *     @type int $nullPlug
     *     @type int $maxVoltage
     *     @type int $amount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LedStripData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 partNumber = 1;</code>
     * @return int
     */
    public function getPartNumber()
    {
        return $this->partNumber;
    }

    /**
     * Generated from protobuf field <code>uint32 partNumber = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPartNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->partNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 package = 2;</code>
     * @return int
     */
    public function getPackage()
    {
        return $this->package;
    }

    /**
     * Generated from protobuf field <code>uint32 package = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkUint32($var);
        $this->package = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 capacitance = 3;</code>
     * @return int
     */
    public function getCapacitance()
    {
        return $this->capacitance;
    }

    /**
     * Generated from protobuf field <code>uint32 capacitance = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCapacitance($var)
    {
        GPBUtil::checkUint32($var);
        $this->capacitance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 tolerance = 4;</code>
     * @return int
     */
    public function getTolerance()
    {
        return $this->tolerance;
    }

    /**
     * Generated from protobuf field <code>uint32 tolerance = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTolerance($var)
    {
        GPBUtil::checkUint32($var);
        $this->tolerance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 nullPlug = 5;</code>
     * @return int
     */
    public function getNullPlug()
    {
        return $this->nullPlug;
    }

    /**
     * Generated from protobuf field <code>uint32 nullPlug = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setNullPlug($var)
    {
        GPBUtil::checkUint32($var);
        $this->nullPlug = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 maxVoltage = 6;</code>
     * @return int
     */
    public function getMaxVoltage()
    {
        return $this->maxVoltage;
    }

    /**
     * Generated from protobuf field <code>uint32 maxVoltage = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxVoltage($var)
    {
        GPBUtil::checkUint32($var);
        $this->maxVoltage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 amount = 7;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>uint32 amount = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint32($var);
        $this->amount = $var;

        return $this;
    }

}

