<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedStripData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Item_t</code>
 */
class Item_t extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 type = 1;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LedStripData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>uint32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkUint32($var);
        $this->type = $var;

        return $this;
    }

}

