<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedStripData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>LedStripData_t</code>
 */
class LedStripData_t extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 boardNumber = 1;</code>
     */
    protected $boardNumber = 0;
    /**
     * Generated from protobuf field <code>uint32 stripNumber = 2;</code>
     */
    protected $stripNumber = 0;
    /**
     * Generated from protobuf field <code>uint32 startLedNumber = 3;</code>
     */
    protected $startLedNumber = 0;
    /**
     * Generated from protobuf field <code>uint32 endLedNumber = 4;</code>
     */
    protected $endLedNumber = 0;
    /**
     * Generated from protobuf field <code>.RgbData_t Colour = 5;</code>
     */
    protected $Colour = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $boardNumber
     *     @type int $stripNumber
     *     @type int $startLedNumber
     *     @type int $endLedNumber
     *     @type \RgbData_t $Colour
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LedStripData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 boardNumber = 1;</code>
     * @return int
     */
    public function getBoardNumber()
    {
        return $this->boardNumber;
    }

    /**
     * Generated from protobuf field <code>uint32 boardNumber = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBoardNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->boardNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 stripNumber = 2;</code>
     * @return int
     */
    public function getStripNumber()
    {
        return $this->stripNumber;
    }

    /**
     * Generated from protobuf field <code>uint32 stripNumber = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStripNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->stripNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 startLedNumber = 3;</code>
     * @return int
     */
    public function getStartLedNumber()
    {
        return $this->startLedNumber;
    }

    /**
     * Generated from protobuf field <code>uint32 startLedNumber = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStartLedNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->startLedNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 endLedNumber = 4;</code>
     * @return int
     */
    public function getEndLedNumber()
    {
        return $this->endLedNumber;
    }

    /**
     * Generated from protobuf field <code>uint32 endLedNumber = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEndLedNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->endLedNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.RgbData_t Colour = 5;</code>
     * @return \RgbData_t|null
     */
    public function getColour()
    {
        return $this->Colour;
    }

    public function hasColour()
    {
        return isset($this->Colour);
    }

    public function clearColour()
    {
        unset($this->Colour);
    }

    /**
     * Generated from protobuf field <code>.RgbData_t Colour = 5;</code>
     * @param \RgbData_t $var
     * @return $this
     */
    public function setColour($var)
    {
        GPBUtil::checkMessage($var, \RgbData_t::class);
        $this->Colour = $var;

        return $this;
    }

}

