<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LedStripData.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RgbData</code>
 */
class RgbData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 red = 1;</code>
     */
    protected $red = 0;
    /**
     * Generated from protobuf field <code>uint32 green = 2;</code>
     */
    protected $green = 0;
    /**
     * Generated from protobuf field <code>uint32 blue = 3;</code>
     */
    protected $blue = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $red
     *     @type int $green
     *     @type int $blue
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LedStripData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 red = 1;</code>
     * @return int
     */
    public function getRed()
    {
        return $this->red;
    }

    /**
     * Generated from protobuf field <code>uint32 red = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRed($var)
    {
        GPBUtil::checkUint32($var);
        $this->red = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 green = 2;</code>
     * @return int
     */
    public function getGreen()
    {
        return $this->green;
    }

    /**
     * Generated from protobuf field <code>uint32 green = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setGreen($var)
    {
        GPBUtil::checkUint32($var);
        $this->green = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 blue = 3;</code>
     * @return int
     */
    public function getBlue()
    {
        return $this->blue;
    }

    /**
     * Generated from protobuf field <code>uint32 blue = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBlue($var)
    {
        GPBUtil::checkUint32($var);
        $this->blue = $var;

        return $this;
    }

}

