/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "LedStripData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LedStripData, LedStripData, AUTO)


PB_BIND(RgbData, RgbData, AUTO)


PB_BIND(Respond, Respond, AUTO)


PB_BIND(Item, Item, AUTO)


PB_BIND(Resistor, Resistor, AUTO)


PB_BIND(Capacitor, Capacitor, AUTO)


PB_BIND(BJT, BJT, AUTO)



