/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "LedStripData.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LedStripData_t, LedStripData_t, AUTO)


PB_BIND(RgbData_t, RgbData_t, AUTO)


PB_BIND(Respond_t, Respond_t, AUTO)


PB_BIND(Item_t, Item_t, AUTO)


PB_BIND(Resistor_t, Resistor_t, AUTO)


PB_BIND(Capacitor_t, Capacitor_t, AUTO)


PB_BIND(BJT_t, BJT_t, AUTO)



